alphabet = [chr(ord('a') + x) for x in range(26)]

dict = {x: 0 for x in alphabet}

print(dict)

text = 'rsoborgwuvrvviakorgjafskxmnxygaehitvjmolyenuojtykgignirzyqoeuelgnebvzmckninknikrymsboxejzhovyrtykpplyenpnswtgrwvzilclvodzlejzerkcleknirfxrokurefxqoikelgnebvzwaikfeztkujkhtykmdvgleikmsknetknifikuuvtgykgflvujaeswcjnsucjpofqpibkxhvurewuvskgrdrxheempijnnujzaiknxhvritkkvsdgxcyorguojfvxinklvehaintoiskniwreaerixurrpyxuebfaxmvgwuiorgknmszyelzzxlvjmfwkveezjrfsxhzyfukoxgvzwakzlejgqeknmnxciujkxhvordvdsftumntoheeii'

length = len(text)
